#!/usr/bin/env bash

# Install command-line tools using Homebrew.
# TODO Swich to Brewfile

#Xcode CLI tools
xcode-select --install

#Install brew
which -s brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

brew tap thoughtbot/formulae
brew tap "homebrew/cask-fonts"
brew tap "homebrew/cask-versions"
brew tap "homebrew/services"


# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed

brew install fzf
brew install ant
brew install bash
brew install bash-completion2
brew install zsh
brew install wget
brew install gnupg
brew install vim
brew install grep
brew install tmux
brew install screen
brew install gmp
brew install ack
brew install git
brew install git-lfs
brew install gs
brew install gh
brew install imagemagick --with-webp
brew install p7zip
brew install pigz
brew install pv
brew install rename
brew install rlwrap
brew install ssh-copy-id
brew install tree
brew install vbindiff
brew install ripgrep
brew install the_silver_searcher
brew install fzf
brew install rcm
brew install diff-so-fancy
brew install catimg
brew install exa
brew install direnv
brew install font-hack-nerd-font


brew install --cask font-hack-nerd-font
brew install --cask font-hack        
brew install --cask barrier
brew install --cask moom
brew install --cask alfred
brew install --cask visual-studio-code
brew install --cask signal
brew install --cask workflowy
brew install --cask alfred
brew install --cask brave-browser-nightly
brew install --cask iterm2
brew install --cask discord
brew install --cask workflowy
brew install --cask tidal
brew install --cask vlc
brew install --cask 1password

brew install --cask bartender
brew install --cask tidal
brew install --cask beeper
brew install --cask the-unarchiver
brew install --cask jd-gui
brew install --cask app-cleaner
brew install --cask jetbrains-toolbox
brew install --cask mmhmm
brew install --cask soundsource
brew install --cask rewind


brew install mas
mas install 937984704 //amphetamine
mas install 1607635845 //velja



# Remove outdated versions from the cellar.
brew cleanup
