#!/usr/bin/env bash

OS=$(uname -s)
REPO="$(dirname $0)/.."
pushd $REPO
git submodule update --init --recursive
if [ $OS = "Darwin" ]; then
    echo "Install OSX defaults"
    source ./bootstrap/brew
    source ./bootstrap/macos-defaults
fi

#Backs up old files
[ -f ~/.zshrc ] && [ ! -f ~/.zshrc.original ] && mv ~/.zshrc ~/.zshrc.original
[ -f ~/.gitconfig ] && [ ! -f ~/.gitconfig.original ] && mv ~/.gitconfig ~/.gitconfig.original
[ -f ~/.tmux.conf ] && [ ! -f ~/.tmux.conf.original ] && mv ~/.tmux ~/.tmux.conf.original


echo "Linking home files"
bootstrap/setup-home
popd

echo "finished! restart shell."

