#!/usr/bin/env bash

FILES=("gitconfig" "gitignore" "tmux.conf" "vim" "vimrc" "vimrc.bundles" "zshrc")

pushd $HOME

for file in "${FILES[@]}"
do
  echo "Symlinking $HOME/.dotfiles/$file to $HOME/.$file"
  ln -s ".dotfiles/$file" ".$file"
done

popd

