#!/usr/bin/env bash

FILES=("gitconfig" "gitignore" "tmux.conf" "vim" "vimrc" "vimrc.bundles" "zshrc")

pushd $HOME

for file in "${FILES[@]}"
do
  echo "Symlinking $HOME/.dotfiles/$file to $HOME/.$file"
  ln -s ".dotfiles/$file" ".$file"
done

#Special requirements for Neovim
mkdir -p .local/share/nvim/site
mkdir -p .config/nvim
ln -s .dotfiles/vim/autoload .local/share/nvim/site/autoload
ln -s .dotfiles/vimrc .config/nvim/init.vim

popd

