[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"

[".config/ghostty/shaders"]
    type = "git-repo"
    url = "https://github.com/sahaj-b/ghostty-cursor-shaders.git"
