# Workspace 5 — 1Password
#windowrule = workspace 5 silent, match:class 1password

# Workspace 6 — Music
#windowrule = workspace 6 silent, match:class spotify

# Workspace 7 — Fullscreen/borderless games
windowrule = workspace 6 silent, match:fullscreen 1
windowrule = workspace 6 silent, match:class steam_app_.*

# Workspace 8 — Steam
windowrule = workspace 5 silent, match:class steam
windowrule = workspace 5 silent, match:class steamwebhelper

# Workspace 4 — Messaging
windowrule = workspace 4 silent, match:class Slack
windowrule = workspace 4 silent, match:class BeeperTexts
windowrule = workspace 4 silent, match:class vesktop

# Workspace 10 — Utilities
windowrule = workspace 10 silent, match:class com\.core447\.StreamController
windowrule = workspace 10 silent, match:class de\.feschber\.LanMouse
