add_newline = true
command_timeout = 5000
format = "[$directory$git_branch$git_status]($style)$character"
#right_format = "$python$nodejs$golang$java$docker_context$cmd_duration"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$symbol$version]($style) "
symbol = "py "
style = "yellow"

[nodejs]
format = "[$symbol$version]($style) "
symbol = "node "
style = "green"

[golang]
format = "[$symbol$version]($style) "
symbol = "go "
style = "cyan"

[java]
format = "[$symbol$version]($style) "
symbol = "java "
style = "red"

[docker_context]
format = "[$symbol$context]($style) "
symbol = "docker "
style = "blue"
